// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
//
// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
export const firebaseConfig = {
  apiKey: "AIzaSyAEe2ayxZevgU9-Nvv8HiD2mYLsdvQyJ2k",
  authDomain: "student-managment-system-a9c4e.firebaseapp.com",
  projectId: "student-managment-system-a9c4e",
  storageBucket: "student-managment-system-a9c4e.appspot.com",
  messagingSenderId: "521962782265",
  appId: "1:521962782265:web:c2458650f72353cfee57e8"
};
